### ISSUE TITLE
rss and atom not working

### ISSUE THREAD

**Issue by CommonJoe** [SoylentNews/rehash#213] opened 2015-09-08 04:51 UTC
I use the rss function.  As of September 7, 12:43 PM, I have not downloaded anymore new stories, although I can see new stories have appeared on the website.  Looking at the atom and rss links on a web browser, it appears both are affected.

**Comment by paulej72** [comment] 2015-09-08 15:02
Fixed

**Comment by CommonJoe** [comment] 2015-09-08 16:07
Thank you!  :)

Common Joe

**Comment by TheMightyBuzzard** [comment] 2015-10-02 17:19
Closing as this was caused by slashd crashing.

**Closed by TheMightyBuzzard** 2015-10-02 17:19 UTC
