### ISSUE TITLE
Server Error when preview comment having char < 0x1f, or char==0x7f

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#29] opened 2015-04-24 15:56 UTC
_From @marty-b on March 29, 2015 21:28_

Tried to submit a comment to: https://dev.soylentnews.org/article.pl?sid=15/03/29/1622202
1.)  Viewed story
2.)  Clicked on Reply button
3.)  Entered comment title: "0x7f - POT"
4.)  Selected "Plain Old Text" from the Drop-Down list
5.)  Clicked on 'Preview' button.
6.)  Got server error:
OK

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, slash@dev.soylentnews.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

7.) paulej72 provided this snippet from logs:

[Sun Mar 29 20:49:50 2015] [error] /comments.pl:ModPerl::ROOT::ModPerl::Registry::srv_soylentnews_2eorg_rehash_site_soylent_2dmainpage_htdocs_comments_2epl:/srv/soylentnews.org/rehash/site/soylent-mainpage/htdocs/comments.pl:506:cannot getSkin for empty skid='0' ;; Which was called by:ModPerl::ROOT::ModPerl::Registry::srv_soylentnews_2eorg_rehash_site_soylent_2dmainpage_htdocs_comments_2epl:/srv/soylentnews.org/rehash/site/soylent-mainpage/htdocs/comments.pl:329
[Sun Mar 29 20:51:00 2015] [error] Cannot decode string with wide characters at /srv/soylentnews.org/perl/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Encode.pm line 241.\n

_Copied from original issue: SoylentNews/slashcode#435_

**Comment by paulej72** [comment] 2015-04-24 15:56
_From @marty-b on March 29, 2015 21:30_

Missing one step:
3.5) In the text entry area, insert a single character: 0x7f, i.e. ""

**Comment by paulej72** [comment] 2015-04-24 15:56
_From @NCommander on March 30, 2015 5:15_

Ugh. I'm guessing this is a problem with perl 5.20 vs. mod_perl 2. Paging
TMB.

**Comment by NCommander** [comment] 2015-04-30 08:06
I can't reproduce this anymore; I copy and pasted in quite a few single unicode characters, including 0x7f (division sign), and failed to get the server to up and chuck. I think we can close this, but I'd like @martyb to reconfirm it

**Comment by marty-b** [comment] 2015-04-30 15:25
Not fixed.
See story:: <a href="https://dev.soylentnews.org/breakingnews/article.pl?sid=15/04/30/1353231">https://dev.soylentnews.org/breakingnews/article.pl?sid=15/04/30/1353231</a>
And, specifically, this comment to it:
<a href="https://dev.soylentnews.org/breakingnews/comments.pl?sid=1223&cid=28403">https://dev.soylentnews.org/breakingnews/comments.pl?sid=1223&cid=28403</a>

**Comment by NCommander** [comment] 2015-05-02 04:35
I appear to have accidently fixed this on dev: the following text: <a href="http://www.google.com/search?q="♥">proper</a> no longer 500s. However, the link is missing the unicode char; this behavior is consistent with production. I have no idea how I fixed it, I didn't make a code change but I was screwing with Apache's configuration to move the vhost log into error log to get feedback.

**Comment by NCommander** [comment] 2015-05-02 04:36
a href="http://www.google.com/search?q="♥"proper/a

removing < > to get this to post

**Comment by NCommander** [comment] 2015-05-02 04:37
This appears strongly related to the issue: http://blog.endpoint.com/2010/12/character-encoding-in-perl-decodeutf8.html

**Comment by TheMightyBuzzard** [comment] 2015-05-06 14:05
Believed to be fixed in #37

**Closed by TheMightyBuzzard** 2015-05-06 14:05 UTC
Labels: Bug: Critical, Priority: High
