### ISSUE TITLE
Links on main page fail to specify charset or have wrong charset specified

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#173] opened 2015-06-15 20:11 UTC
These links from the main page of https://soylenews.org/ seem to not provide a charset:
   https://soylentnews.org/base.css?rehash_15_05
   https://soylentnews.org/comments.css?rehash_15_05
   https://soylentnews.org/print.css?rehash_15_05
   https://soylentnews.org/soylentnews.css?rehash_15_05

This link says its charset is:iso-8859-1
   https://soylentnews.org/article.pl?sid=15/06/04/2158244

   NOTE: The above link appears as a link within the text:
      "See our story on the earlier breach."
   And appears in the context of this story on the main page:
      https://soylentnews.org/article.pl?sid=15/06/14/034207

(Problems discovered while running Xenu link sleuth on the SoylentNews home page; see prior bug for steps to reproduce.)

**Comment by TheMightyBuzzard** [comment] 2016-09-26 18:22
Exceedingly difficult to reproduce, though the css files are coming in with a non-utf-8 Content-type header.

**Comment by TheMightyBuzzard** [comment] 2016-09-26 19:33
Solved the .css content types. One line in soylent-mainpage.conf. It'll go live next time apache is bounced.

Can't reproduce any of the other buggy content types, so closing.

**Closed by TheMightyBuzzard** 2016-09-26 19:33 UTC
Labels: Bug: Non-Critical, Priority: Normal
