### ISSUE TITLE
Comment Links in Messages odd behaviour after cut across to Rehash

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#75] opened 2015-06-02 04:32 UTC
Specific:
Affects Messages received pre cut over to Rehash

Where:
Message received when another user replies to a comment made on a story.

Symptom:
The 2nd link in the message that links to my own comment that was replied to. On first attempt, clicking that link, brings up the story text and the rest of the site graphics, but the comment is absent. On second attempt, the linked comment is displayed. Replicated twice in testing.

Triage:
Unable to replicate this with a message generated post cut over to rehash. 
It only seems to affect messages sent as a result of a reply to a Comment on a Story, messages sent as a result of a reply to a Comment on a user's Journal seem to behave fine.

Synopsis:
Likely a cut over to rehash glitch. Observation for reoccurance.

**Comment by paulej72** [comment] 2015-06-02 13:20
probably due nexus issues.  Need to see what is up once we fix the getSkins bug

**Comment by TheMightyBuzzard** [comment] 2016-09-27 15:10
Closing this as we're not in a position to be able to reproduce it anymore since all messages older than two weeks are deleted and it's been way longer than that.

**Closed by TheMightyBuzzard** 2016-09-27 15:10 UTC
Labels: Bug: Non-Critical, Priority: Normal
