### ISSUE TITLE
Problem loading page (The connection has timed out)

### ISSUE THREAD

**Issue by shanen0** [SoylentNews/rehash#395] opened 2017-05-29 19:29 UTC
"Problem loading page" on the tab and "The connection has timed out" in the main panel are the error messages from Firefox, but I've tried two other browsers and also failed to connect with different error messages. This first happened about two or three months ago and lasted for several weeks, and this time it has been going on for several days already. 

Last time it suddenly started working, and when I asked on the website, the response was that they hadn't noticed anything. That made me suspect it might be a local routing problem of some sort, even though my ISP is a big one and I'm not seeing any similar problems with any other websites. Tracert to soylentnews.org goes 17 hops before the packets start dying, but that should be quite close to the webhost there. (It is reaching one router past theplanet backbone, having spent most of the trip in networklayer.)

A few days I was trying to figure it out and discovered that using a VPN from an American IP address makes the website partly available. That led me to suspect it might be a DNS problem, but using the IP address directly does not seem to be a solution. Either that fails in the same was as the soylentnews.org or it produces a different error message about a certificate problem.

Pretty sure it is something wrong with the configuration of the SN website, but not sure what other diagnostic steps to take. However, I'm pretty sure that this is not the best reporting channel... More certain that even if I was willing to help pay for the fix, that isn't how Github works.

**Comment by TheMightyBuzzard** [comment] 2017-05-29 20:01
@shanen0 You wouldn't by chance be coming in from Turkey, would you? We know for certain Turkey has explicitly blocked our site before.

Using a VPN terminated outside the affected area should make the site work perfectly, as should proxies. If all else fails, there's always ToR.

**Comment by shanen0** [comment] 2017-05-30 10:07
No, Japan. However that explains the new problem, but I wasn't able to log in properly through the VPN, either, even when I was using the domain name.

Still broken, but that reminds me that I've only tests Windows and Mac OS. I should give it a try on a Linux box, too. Maybe on Thursday...

**Comment by TheMightyBuzzard** [comment] 2017-05-30 10:45
@shanen0 One other question, were you using www.soylentnews.org or just soylentnews.org? Because we do not use/test/support www and it breaks quite often.

**Comment by shanen0** [comment] 2017-06-11 23:45
Not certain if this will properly come to your [TheMightyBuzzard's] attention, but I tried both URLs before the IP address experiments. Just tried them again, and still no connection to the website. So I guess that makes about 2 weeks this time.

I guess I feel like I should apologize for not feeling like I want to spend much more time on this, but mostly I feel like SN was another good idea that flashed in the pan. As usual, I blame bad financial models, but that's getting out of scope. (Or perhaps it isn't completely out of scope if you at least sometimes feel you should get paid for your work on behalf of SN?)

**Comment by TheMightyBuzzard** [comment] 2017-06-13 10:08
No worries. Wish I could help but it appears you've got both ISP (corporate? are you trying to connect from work?) blockade of our domain and a misconfigured VPN setup either on your end or your VPN provider's end. I can't reproduce the issue through any of the VPNs I can easily access, so there's not much we can do from our end of things.

**Comment by TheMightyBuzzard** [comment] 2017-12-08 12:53
Closing due to inability to reproduce.

**Closed by TheMightyBuzzard** 2017-12-08 12:53 UTC
